# NumPy

* NumPy yra tiesinės algebros biblioteka. Jos pagrindu sukurtos beveik visos su duomenų mokslu susijusios bibliotekos, tokios kaip Pandas ir kt. Numpy yra itin greita, nes yra susieta ryšiais(bindings) su C kalba parašytais moduliais. 

* Standartiškai įsidiegia *pip install numpy*, jeigu naudojate Anaconda - *conda install numpy*
* Dažniausiai naudojamas NumPy ingredientas - NumPy masyvai. Jie būna dviejų tipų - vektoriai ir matricos.  

Prieš pradedant darbą su NumPy, reikia jį importuoti.

In [ ]:
import numpy as np

tarkime, turime paprastą Python list'ą:

In [ ]:
listas = [1, 2, 3, 4, 5]

paveskime jį į NumPy array:

In [ ]:
arr = np.array(listas)

In [ ]:
arr


In [ ]:
# atspausdins sarasa be kableliu
print(arr)

gauname 1 lygio NumPy masyvą (vektorių). Jeigu norime matricos, turime sukurti keletą masyvų masyve:

In [ ]:
# sarsai sarase!, kad gautume MATRICA
mano_listai = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matrica = np.array(mano_listai)


In [ ]:
# atspausdins array matrica
matrica

In [ ]:
# atspausdins matrica be kableliu
print(matrica)

NumPy turi ir integruotus, paprastus būdus susikurti masyvą. Skliausteliuose reikia įrašyti start, stop ir step(nebūtina) reikšmes:

In [41]:
# masyvas nuo 0-start iki 30-stop kas trecia zingsni 3-step 
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# atspausdins masyva nuo 0 iki 30 (30 neitrauktas), nes nenurodeme STEP
np.arange(0, 30)

In [ ]:
# su print funkcija mes gausime masyva/sarasa be kableliu
print(np.arange(0, 30))

jeigu reikia vektoriaus iš nulių:

In [ ]:
# nurodome kiek NULIU array vektoriuje
np.zeros(10)

In [ ]:
# nurodome kiek NULIU array vektoriuje/sarase be kableliu
print(np.zeros(10))

jeigu matricos iš nulių:

In [ ]:
# nurodome kiek 0 ir kiek eiluciu MATRICOJE
np.zeros((5,5))

In [ ]:
# nurodome kiek 0 ir kiek eiluciu MATRICOJE be kableliu
print(np.zeros((5,5)))

Analogiškai veikia np.ones metodas.
Dar viena naudinga funkcija - linspace. Ji grąžina masyvą, su lygiais intervalais išdėliotomis reikšmėmis. Reikia nurodyti start, stop ir intervalo reikšmes:

In [ ]:
np.linspace(0,20,16)

Jeigu prireikė vienetinės matricos:

In [ ]:
# vinetukus atspausdina ustryzai
np.eye(6)

In [ ]:
print(np.eye(6))

# Random arrays kūrimas

Pirmas metodas susikurti random array - **np.random.rand()**. Jo pagalba galime susikurti masyvą su atsitiktinėm reikšmėm nuo 0 iki 1 *("uniform" distribution)*

In [ ]:
# uztenka nurodyti viena reiksme kad isvestu 10 atsitiktiniu reiksmiu
np.random.rand(10)

In [ ]:
# reikia dvieju reiksmiu kad isvestu viena atsitiktine reiksme
np.random.randint(10, 189)

jeigu norime ne vektoriaus, o matricos:

In [ ]:
np.random.rand(5,5)

**np.random.randn()** sugeneruos reikšmes iš  *“standard normal” distribution* (standartinis normalusis skirstinys)

In [ ]:
np.random.randn(3,3)

**np.random.randint()** sugeneruoja atsitiktines integer reikšmes. Parametruose reikia nurodyti, žemiausią, aukščiausią (neįskaitant) reikšmes ir norimą kiekį reikšmių.

In [ ]:
np.random.randint(100, 200, 20)

# Masyvų pertvarkymas

**reshape()** metodas leidžia mums performuoti turimą masyvą į kitą formą:

In [ ]:
# randint reikia nurodyti maziausia ir didziausia reiksmes, bei nurodyti kiek atspausinti reiksmiu (siu atveju 64) 
my_array = np.random.randint(0, 100, 64)

In [ ]:
my_array

In [ ]:
# cia nurodome pakeisti musu sarasa i lentele 8 ant 8 formos
reshaped_array = my_array.reshape(8,8)

In [ ]:
reshaped_array

šiame pavyzdyje vektorių iš 64 reikšmių performavome į 8x8 matricą.

In [ ]:
# cia nurodome pakeisti musu lentele atgal i sarasa
returned_back_array = my_array.reshape(64)

In [ ]:
returned_back_array

In [ ]:
# randint reikia nurodyti maziausia ir didziausia reiksmes, nurodyti kiek atspausinti reiksmiu - NEGALIMA!
# bei suformuojame matrica is kart
my_array_matrica = np.random.randint(0, 100, (8, 8))

In [ ]:
my_array_matrica

# Naudingi Metodai

**max()** ir **.min()** metodai ištraukia maksimalią ir minimalią reikšmes iš masyvo:

In [ ]:
my_array.min()

In [ ]:
my_array.max()

**argmax()** ir **argmin()** nurodo mums maksimalios ir minimalios reikšmių indeksą:

In [ ]:
my_array.argmax()

In [ ]:
my_array.argmin()

**.shape** nurodo, kokią formą turi mūsų masyvas:

In [ ]:
reshaped_array.shape

**.dtype** nurodo, koks duomenų tipas yra mūsų masyve:

In [ ]:
reshaped_array.dtype

# Indeksacija ir reikšmių traukimas

In [ ]:
sample_array = np.arange(1,10)

In [ ]:
# 10 neitraukiama
sample_array

reikšmę iš vektoriaus traukiame taip pat kaip ir iš Python sąrašo:

In [ ]:
sample_array[5]

galime naudoti *slices*:

In [ ]:
sample_array[2:8]

In [ ]:
sample_array[6:]

In [ ]:
sample_array[-5:]

galime pasirinktam rėžiui suteikti kokią nors savo reikšmę *(Broadcasting)*: 

In [ ]:
sample_array[4:8] = 50

In [ ]:
sample_array

# Reikšmių traukimas iš matricos 

In [45]:
sample = np.random.randint(1, 10, 25)

In [46]:
sample_matrix = sample.reshape(5,5)

In [47]:
sample_matrix

array([[2, 9, 4, 5, 1],
       [9, 5, 1, 6, 9],
       [3, 4, 5, 7, 9],
       [2, 4, 5, 5, 8],
       [3, 2, 7, 1, 6]])

In [49]:
sample_matrix[2,2] 

5

laužtiniuose skliausteliuose pirmiau nurodome eilutę, paskui tos eilutės nario indeksą.

taip pat galime naudoti rėžius:

In [50]:
sample_matrix[1:4, 1:4]

array([[5, 1, 6],
       [4, 5, 7],
       [4, 5, 5]])

In [ ]:
sample_matrix

In [ ]:
sample_matrix[3:,:]

In [ ]:
sample_matrix[:, 0:2]

# Reikšmių traukimas pagal sąlygą

Tarkime, turime masyvą:

In [ ]:
masyvas = np.arange(1,21)

In [ ]:
masyvas

norime reikšmių, didesnių už 9:

In [ ]:
bool_masyvas = masyvas > 9

In [ ]:
bool_masyvas

gauname masyvą iš *bool* reikšmių, kuriame True reikšmės atitinka užduotą sąlygą. Atlikime tokią operaciją:

In [ ]:
masyvas[bool_masyvas]

kintamojo *masvas* laužtiniuose skliautuose įvedę kintamąjį *bool_masyvas*, gauname reikšmes, kurios atitinka True indeksą. Tą patį rezultatą galime gauti laužtiniuose skliaustuose tiesiog įrašę sąlygą:

In [ ]:
masyvas[masyvas>9]

# Numpy elgsenos ypatumai

Yra tam tikri NumPy elgsenos ypatumai, tarkime:

In [ ]:
pvz = np.random.randint(1, 21, 20)

In [ ]:
pvz

turime *random* masyvą iš integer reikšmių. Susikurkime jo atraižą:

In [ ]:
pvz_ispjova = pvz[5:15]

In [ ]:
pvz_ispjova

In [ ]:
pvz_ispjova[:] = 99

In [ ]:
pvz_ispjova

Iki šio momento viskas atrodo kaip ir tikėtąsi. Tačiau išsikvietę pirmąjį masyvą matome:

In [ ]:
pvz

Paprastai kuriant kintamąjį, užkulisiuose padaroma kopija šaltinio, iš kurio jis gaminamas (šiuo atveju *pvz*). 
Iš tos kopijos formuojamas naujas kintamasis. Tačiau NumPy atveju pakeitimai vykdomi originale, ir mums 
rodoma tik modifikuota to originalo dalis. NumPy pritaikytas darbui su milžiniškais kiekiais duomenų. Daryti laikinas jų kopijas atmintyje yra neefektyvu, ir nestabilu. Todėl, kai norime išsaugoti originalą, turime nurodyti, kad norėsime pasidaryti kopiją:

In [20]:
import numpy as np

In [21]:
pvz = np.random.randint(1, 21, 20)

In [22]:
pvz

array([13, 10, 18, 16,  9,  8,  1,  7,  5, 10, 14,  4, 19, 18, 15, 13,  2,
        8,  8,  6])

In [23]:
pvz_copy = pvz.copy()

In [24]:
pvz_copy

array([13, 10, 18, 16,  9,  8,  1,  7,  5, 10, 14,  4, 19, 18, 15, 13,  2,
        8,  8,  6])

In [25]:
pvz_copy == pvz

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [26]:
pvz_copy_ispjova = pvz_copy[5:15]
pvz_copy_ispjova[:] = 100

In [27]:
pvz_copy_ispjova

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
pvz

array([13, 10, 18, 16,  9,  8,  1,  7,  5, 10, 14,  4, 19, 18, 15, 13,  2,
        8,  8,  6])

In [29]:
pvz_copy

array([ 13,  10,  18,  16,   9, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100,  13,   2,   8,   8,   6])

Taigi, pasidarėme kopiją, nurodėme kad norime jos rėžio [5:15] kintamąjame *pvz_copy_ispjova*, joje visas reikšmes pakeitėme į 100, ir įsitikinome, kad po to originalusis *pvz* liko nepakeistas.

# Matematinės operacijos ir funkcijos

su NumPy arrays galima atlikti paprastus aritmetinius veiksmus:

In [30]:
vektorius = np.arange(1,11)

In [31]:
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
vektorius + vektorius

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
vektorius * vektorius

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [34]:
vektorius / vektorius

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
vektorius / 0

/var/folders/n6/nzyv9f853k7djbyfmdph5t5w0000gn/T/ipykernel_6070/17242066.py:1: RuntimeWarning: divide by zero encountered in divide
  vektorius / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

atkreipkite dėmesį, atlikus dalybą iš 0 gausime begalybes arba nan - not a number. Taip pat galime atlikti veiksmus ir su skaičiais:

In [37]:
vektorius + 1000

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [38]:
vektorius ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

ir t.t.

Numpy aplinkoje taip pat galime taikyti įvairias trigonometrines funkcijas ir tt.

In [39]:
np.sin(vektorius)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [40]:
np.log(vektorius)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

Visas matematines funkcijas galite surasti
[čia](https://docs.scipy.org/doc/numpy/reference/ufuncs.html).